export const stakingFactoryAbi = [
   {
      "type":"function",
      "name":"createStakingContract",
      "inputs":[
         {
            "name":"_stakingToken",
            "type":"address",
            "internalType":"address"
         },
         {
            "name":"_admin",
            "type":"address",
            "internalType":"address"
         }
      ],
      "outputs":[
         {
            "name":"",
            "type":"address",
            "internalType":"address"
         }
      ],
      "stateMutability":"nonpayable"
   },
   {
      "type":"function",
      "name":"getAllStakingContracts",
      "inputs":[
         
      ],
      "outputs":[
         {
            "name":"",
            "type":"tuple[]",
            "internalType":"struct StakingFactory.StakingInfo[]",
            "components":[
               {
                  "name":"stakingContract",
                  "type":"address",
                  "internalType":"address"
               },
               {
                  "name":"stakingToken",
                  "type":"address",
                  "internalType":"address"
               }
            ]
         }
      ],
      "stateMutability":"view"
   },
   {
      "type":"function",
      "name":"getAllStakingStats",
      "inputs":[
         
      ],
      "outputs":[
         {
            "name":"totalStaked",
            "type":"uint256",
            "internalType":"uint256"
         },
         {
            "name":"totalRewardRate",
            "type":"uint256",
            "internalType":"uint256"
         }
      ],
      "stateMutability":"view"
   },
   {
      "type":"function",
      "name":"stakingContracts",
      "inputs":[
         {
            "name":"",
            "type":"uint256",
            "internalType":"uint256"
         }
      ],
      "outputs":[
         {
            "name":"stakingContract",
            "type":"address",
            "internalType":"address"
         },
         {
            "name":"stakingToken",
            "type":"address",
            "internalType":"address"
         }
      ],
      "stateMutability":"view"
   },
   {
      "type":"event",
      "name":"StakingContractCreated",
      "inputs":[
         {
            "name":"stakingContract",
            "type":"address",
            "indexed":true,
            "internalType":"address"
         },
         {
            "name":"stakingToken",
            "type":"address",
            "indexed":true,
            "internalType":"address"
         }
      ],
      "anonymous":false
   },
   {
      "type":"error",
      "name":"ReentrancyGuardReentrantCall",
      "inputs":[
         
      ]
   }
] as const;
  